# Generated by Django 3.1.7 on 2021-03-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('s', 'Маленькое'), ('m', 'Среднее'), ('l', 'Большое')], default='s', max_length=2)),
                ('count_bomb', models.IntegerField()),
            ],
        ),
    ]
